POST http://localhost:3333/events
Content-Type: application/json

{
	"title": "Novo evento",
	"details": null,
	"maximumAttendees": 1
}

###

POST http://localhost:3333/events/de4c3ada-11ba-4f84-b2a7-9b5646380cb1/attendees
Content-Type: application/json

{
	"name": "Mario",
	"email": "mario@worxbasea.com"
}

###

GET http://localhost:3333/events/de4c3ada-11ba-4f84-b2a7-9b5646380cb1/

###

GET http://localhost:3333/attendees/2/badge

###

GET http://localhost:3333/attendees/2/check-in

###

GET http://localhost:3333/events/de4c3ada-11ba-4f84-b2a7-9b5646380cb1/attendees?query=mario